apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-hub
  template:
    metadata:
      labels:
        app: game-hub
    spec:
      containers:
        - name: game-hub
          image: sumedhudupa/gamehub:latest # Replace with your Docker Hub image
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: game-hub-service
spec:
  type: NodePort
  selector:
    app: game-hub
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
