apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamehub
  template:
    metadata:
      labels:
        app: gamehub
    spec:
      containers:
        - name: gamehub
          image: sumedhudupa/gamehub:latest # Replace with your Docker Hub image
          ports:
            - containerPort: 5173
 
---
apiVersion: v1
kind: Service
metadata:
  name: gamehub-service
spec:
  type: NodePort
  selector:
    app: gamehub
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
